#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'

class ImapFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{Rails.root}/config/imap.yml")
  @config = @config[Rails.env].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
  def self.start
    puts "Starting ImapFetcherDaemon"

    email_accounts = EmailAccount.all
    fetchers = []
    for email_account in email_accounts
      puts "  for account #{email_account}"

      email_account.user.make_current
      email_account_options = {
        :server => email_account.server,
        :username => email_account.username,
        :password => email_account.password
      }
      config = @config.merge(email_account_options)

      # Add your own receiver object below
      fetchers << Fetcher.create({:receiver => nil}.merge(config))
    end

    loop do
      for fetcher in fetchers
        fetcher.fetch
      end
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping ImapFetcherDaemon"
  end
  
end

ImapFetcherDaemon.daemonize
