#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'

class ImapFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{Rails.root}/config/imap.yml")
  @config = @config[Rails.env].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
  def self.start
    puts "Starting ImapFetcherDaemon"
    # Add your own receiver object below
    @fetcher = Fetcher.create({:receiver => nil}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping ImapFetcherDaemon"
  end
  
end

ImapFetcherDaemon.daemonize
