#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'

class ImapFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{Rails.root}/config/imap.yml")
  @config = @config[Rails.env].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
  def self.start
    puts "Starting ImapFetcherDaemon"

    loop do
      for account in EmailAccount.all
        begin
          account.sync_from_imap
        rescue Exception => e
          puts "Failed fetching account #{account}:"
          puts e.message
        end
      end
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping ImapFetcherDaemon"
  end
  
end

ImapFetcherDaemon.daemonize
